baseURL = "http://example.org/"
languageCode = "en-us"
title = "Take Care"
theme = "takecare"

[menu]
  [[menu.main]]
    identifier = "Buy"
    name = "Buy"
    url = "https://heytakecare.bigcartel.com"

  [[menu.main]]
    identifier = "Instagram"
    name = "Instagram"
    url = "https://instagram.com/heytakecare"
