baseURL = "https://heytakecare.github.io"
languageCode = "en-us"
theme = "takecare"
title = "Take Care"
[[menu.main]]
identifier = "Instagram"
name = "Instagram"
url = "https://instagram.com/takecare_mag"
weight = 4
